[package]
name = "advent-2021"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlSelectElement"] }
